import { DuoState } from "./types";

export const initialDuoData: DuoState = {
  code: "LIFT24",
  sharedStreak: 14,
  lastNudge: {
    fromName: "Alex",
    emoji: "🔥",
    message: "Chest day today, don't slack off bro!",
    time: "10 mins ago",
  },
  currentUser: {
    id: "user_siva",
    name: "Siva",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    statusToday: "completed",
    todayWorkoutTitle: "Chest & Shoulders Hypertrophy",
    weeklyGoalDays: 5,
    weeklyCompletedDays: 4,
    streak: 14,
    totalVolumeMonthKg: 18450,
  },
  partner: {
    id: "user_alex",
    name: "Alex",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    statusToday: "pending",
    weeklyGoalDays: 5,
    weeklyCompletedDays: 3,
    streak: 14,
    totalVolumeMonthKg: 16800,
  },
  workouts: [
    {
      id: "w_1",
      userId: "user_siva",
      userName: "Siva",
      userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      title: "Chest & Shoulders Hypertrophy",
      category: "Push",
      date: new Date().toISOString(),
      durationMinutes: 52,
      totalVolumeKg: 6420,
      isPR: true,
      notes: "Crushed 36kg DB incline press! Felt super solid.",
      exercises: [
        {
          name: "Incline DB Press",
          muscleGroup: "Chest",
          sets: [
            { setNumber: 1, weight: 32, reps: 10, completed: true },
            { setNumber: 2, weight: 34, reps: 8, completed: true },
            { setNumber: 3, weight: 36, reps: 7, completed: true, rpe: 9.5 },
          ],
        },
        {
          name: "Pec Deck Flyes",
          muscleGroup: "Chest",
          sets: [
            { setNumber: 1, weight: 65, reps: 12, completed: true },
            { setNumber: 2, weight: 70, reps: 10, completed: true },
            { setNumber: 3, weight: 75, reps: 9, completed: true },
          ],
        },
        {
          name: "Lateral Raises (Cable)",
          muscleGroup: "Shoulders",
          sets: [
            { setNumber: 1, weight: 12, reps: 15, completed: true },
            { setNumber: 2, weight: 14, reps: 12, completed: true },
            { setNumber: 3, weight: 14, reps: 12, completed: true },
          ],
        },
      ],
    },
    {
      id: "w_2",
      userId: "user_alex",
      userName: "Alex",
      userAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
      title: "Back & Biceps Width Focus",
      category: "Pull",
      date: new Date(Date.now() - 86400000).toISOString(),
      durationMinutes: 58,
      totalVolumeKg: 7890,
      isPR: false,
      notes: "Focused on strict form and full lat stretch on pulldowns.",
      exercises: [
        {
          name: "Neutral Grip Lat Pulldown",
          muscleGroup: "Back",
          sets: [
            { setNumber: 1, weight: 70, reps: 12, completed: true },
            { setNumber: 2, weight: 75, reps: 10, completed: true },
            { setNumber: 3, weight: 80, reps: 8, completed: true },
          ],
        },
        {
          name: "Chest Supported T-Bar Row",
          muscleGroup: "Back",
          sets: [
            { setNumber: 1, weight: 50, reps: 10, completed: true },
            { setNumber: 2, weight: 55, reps: 9, completed: true },
            { setNumber: 3, weight: 60, reps: 8, completed: true },
          ],
        },
      ],
    },
  ],
  photos: [
    {
      id: "p_1",
      userId: "user_siva",
      userName: "Siva",
      userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80",
      caption: "Post push day pump! Upper chest line starting to show 💪",
      type: "Pump",
      bodyWeightKg: 74.8,
      date: new Date().toISOString(),
      reactions: [
        { userId: "user_alex", userName: "Alex", emoji: "🔥" },
        { userId: "user_alex", userName: "Alex", emoji: "⚡" },
      ],
    },
    {
      id: "p_2",
      userId: "user_alex",
      userName: "Alex",
      userAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
      imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80",
      caption: "Week 4 check-in. Lat flare looking wider.",
      type: "Physique",
      bodyWeightKg: 78.2,
      date: new Date(Date.now() - 86400000 * 2).toISOString(),
      reactions: [{ userId: "user_siva", userName: "Siva", emoji: "💪" }],
    },
  ],
};
